---
service: glhf

frameworkVersion: '^2.38.0'

variablesResolutionMode: 20210219
configValidationMode: error

disabledDeprecations:
  - CLI_OPTIONS_SCHEMA

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 7
  memorySize: 512
  stackTags:
    Owner: ${self:custom.owner}
    Project: ${self:custom.app}
    Name: ${self:custom.name}
    Deployment: ${sls:stage}
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements: ${file(./serverless/role.yml)}
  environment: ${file(./serverless/environment.yml)}

custom:
  name: glhf
  app: glfh
  owner: pureskillgg
  ssmPrefix: /${self:custom.owner}/${self:custom.app}/${sls:stage}

package:
  individually: true
  patterns: ${file(./serverless/exclude.yml)}

functions: ${file(./serverless/functions.yml)}

resources:
  Resources: ${file(./serverless/resources.yml)}
