---
service: glhf

frameworkVersion: '^2.66.2'

variablesResolutionMode: 20210326
configValidationMode: error

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  architecture: arm64
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 30
  memorySize: 512
  timeout: 30
  tracing:
    apiGateway: false
    lambda: false
  stackTags:
    Owner: ${self:custom.owner}
    Project: ${self:custom.app}
    Name: ${self:custom.name}
    Deployment: ${sls:stage}
  httpApi:
    payload: '2.0'
    disableDefaultEndpoint: true
  apiGateway:
    shouldStartNameWithService: true
  eventBridge:
    useCloudFormation: true
  deploymentBucket:
    blockPublicAccess: true
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements: ${file(./serverless/role.yml)}
  environment: ${file(./serverless/environment.yml)}
  layers:
    - arn:aws:lambda:us-east-1:943013980633:layer:SentryNodeServerlessSDK:40

custom:
  name: glhf
  app: glhf
  owner: pureskillgg
  sentryDsn: ${ssm:/${self:custom.owner}/global/sentry/${self:service}/dsn, ''}
  ssmPrefix: /${self:custom.owner}/${self:custom.app}/${sls:stage}/${self:custom.name}

package:
  individually: true
  exclude: ${file(./serverless/exclude.yml)}

functions: ${file(./serverless/functions.yml)}

resources:
  Resources: ${file(./serverless/resources.yml)}
