---
service: makenew-serverless-nodejs

frameworkVersion: "^2.0.0"

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  tracing:
    apiGateway: true
    lambda: true
  runtime: nodejs12.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: ${opt:stage, env:SERVERLESS_STAGE, 'stg'}
  logRetentionInDays: 7
  memorySize: 512
  stackTags:
    Owner: ${self:custom.owner}
    Project: ${self:custom.app}
    Name: ${self:custom.name}
    Deployment: ${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements: ${file(./serverless/role.yml)}
  environment: ${file(./serverless/environment.yml)}

custom:
  name: serverless-nodejs
  app: makenew
  owner: pureskillgg
  ssmPrefix: /${self:custom.owner}/${self:custom.app}/${self:provider.stage}
  webpack:
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk
    # TODO: Workaround for https://github.com/serverless-heaven/serverless-webpack/issues/306
    packagerOptions:
      scripts:
        - rm -rf node_modules/aws-sdk
package:
  individually: true

functions:
  todo:
    handler: handlers/todo.default
    events:
      - http:
          method: get
          path: /todo
