---
service: makenew-serverless-nodejs

frameworkVersion: '^2.38.0'

variablesResolutionMode: 20210219
configValidationMode: error

disabledDeprecations:
  - CLI_OPTIONS_SCHEMA
  - NEW_PACKAGE_PATTERNS

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  tracing:
    apiGateway: false
    lambda: false
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 3
  memorySize: 512
  stackTags:
    Owner: ${self:custom.owner}
    Project: ${self:custom.app}
    Name: ${self:custom.name}
    Deployment: ${sls:stage}
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements: ${file(./serverless/role.yml)}
  environment: ${file(./serverless/environment.yml)}

custom:
  name: serverless-nodejs
  app: makenew
  owner: pureskillgg
  ssmPrefix: /${self:custom.owner}/${self:custom.app}/${sls:stage}

package:
  individually: true
  exclude: ${file(./serverless/exclude.yml)}

functions: ${file(./serverless/functions.yml)}
