---
service: glhf

frameworkVersion: '^2.0.0'

variablesResolutionMode: 20210219
configValidationMode: error

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  tracing:
    apiGateway: true
    lambda: true
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 7
  memorySize: 512
  stackTags:
    Owner: ${self:custom.owner}
    Project: ${self:custom.app}
    Name: ${self:custom.name}
    Deployment: ${self:custom.stage}
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements: ${file(./serverless/role.yml)}
  environment: ${file(./serverless/environment.yml)}

custom:
  stage: ${opt:stage, env:SERVERLESS_STAGE, self:provider.stage}
  name: glhf
  app: glfh
  owner: pureskillgg
  ssmPrefix: /${self:custom.owner}/${self:custom.app}/${self:custom.stage}

package:
  individually: true
  exclude: ${file(./serverless/exclude.yml)}

functions: ${file(./serverless/functions.yml)}

resources:
  Resources: ${file(./serverless/resources.yml)}
