---
NODE_ENV: production
LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
LOG_ENV: ${sls:stage}
LOG_SYSTEM: ${self:custom.app}
LOG_SERVICE: ${self:custom.name}
LOG_VERSION: ${file(./package.json):version}
SENTRY_DSN: ${self:custom.sentryDsn}
SENTRY_ENVIRONMENT: ${sls:stage}
SENTRY_RELEASE: ${self:service}@${file(./package.json):version}
