---
name: release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to release
        required: true
      ref:
        description: Ref to release
        required: true
        default: master
  repository_dispatch:
    types:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}${{ github.event.client_payload.ref }}
      - name: Start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          env: ${{ github.event.inputs.environment }}${{ github.event.client_payload.environment }}
          desc: ${{ github.event.client_payload.ref }}${{ github.event.client_payload.ref }}
          ref: ${{ github.event.client_payload.ref }}${{ github.event.inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: https://npm.pkg.github.com
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Serverless deploy production
        run: yarn run deploy
        if: ${{ github.event.inputs.environment == 'production' || github.event.client_payload.environment == 'production' }}
        env:
          SERVERLESS_STAGE: prod
      - name: Serverless deploy staging
        run: yarn run deploy
        if: ${{ github.event.inputs.environment == 'staging' || github.event.client_payload.environment == 'staging' }}
        env:
          SERVERLESS_STAGE: stg
      - name: Get status
        id: status
        if: always()
        run: |
          if [ "${JOB_STATUS,,}" == 'success' ]; then
            echo "::set-output name=color::#00ff00"
          else
            echo "::set-output name=color::#ff0000"
          fi
        env:
          JOB_STATUS: ${{ job.status }}
      - name: Notify Discord
        uses: rtCamp/action-slack-notify@v2.1.1
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}/slack
          SLACK_USERNAME: PureSkill.gg Bot
          SLACK_ICON_EMOJI: ':github:'
          SLACK_COLOR: ${{ steps.status.outputs.color }}
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Deployed ${{ github.event.inputs.environment }}${{ github.event.client_payload.environment }}
          SLACK_MESSAGE: ${{ github.event.client_payload.ref }}${{ github.event.inputs.ref }}
          SLACK_FOOTER: ${{ github.repository }}
      - name: Finish deployment
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
